create table if not exists shopping_list(
id integer primary key generated by default as identity,
name text not null,
price decimal(12,2) not null,
date_added TimeStamp default now() not null,
checked bool default false,
category grocery not null
);

-- DROP TYPE IF EXISTS grocery;
create type grocery as enum (
'Main',
'Snack',
'Lunch',
'Breakfast'
)

