insert into blogful_articles (title, content, date_published)
values('Stock Investing', 'What to invest? How to invest?', now() - '21 days'::INTERVAL),
('Stock Investing', 'What to invest? How to invest?', now() - '21 days'::INTERVAL),
('Dividends', 'Why are dividends important?', now() - '21 days'::INTERVAL),
('Medium', 'Where good ideas find you.', now() - '15 days'::INTERVAL),
('Robinhood', 'Commission-free stock trading & investing', now() - '21 days'::INTERVAL),
('Tumblr', 'A place to express yourself, discover yourself, and bond over stuff you love', now() - '10 days'::INTERVAL),
('Instagram', 'A place to express yourself, discover yourself, and bond over stuff you love', now() - '10 days'::INTERVAL),
('Reddit', 'A network of communities based on your interest', now() - '10 days'::INTERVAL),
('Pinterest', 'What to invest? How to invest?', now() - '21 days'::INTERVAL),
('Blogger', 'Publish your passions your way', now() - '5 days'::INTERVAL),
('Snapchat', 'Talk with friends, view live stories, and explore news in discover', now() - '21 days'::INTERVAL),
('TikTok', 'Trends start here.', now() - '11 days'::INTERVAL),
('Myspace', 'Connect with People/Entertainment weekly', now() - '11 days'::INTERVAL),
('Black Planet', 'African-American community where black men and women meet to chat', now() - '15 days'::INTERVAL),
('Linkedin', 'Manage your professional identity. Build and Engage your professional network.', now() - '21 days'::INTERVAL),
('Twitter', 'Breaking news and entertainment to sports and politics.', now() - '6 days'::INTERVAL),
('Bumble', 'Changed way people date, find friends, and perception of meeting online.', now() - '9 days'::INTERVAL),
('Tinder', 'Networking and online dating, connecting for common interest', now() - '21 days'::INTERVAL);
